### PR TITLE
Allow host to be used if x-forwarded-host is not set

### LINKED ISSUE #6: Cannot read property 'indexOf' of undefined
```
Cannot read property 'indexOf' of undefined
TypeError: Cannot read property 'indexOf' of undefined
    at absoluteUrl (/node_modules/next-absolute-url/index.js:4:12)
```

I tried both the 2 param and the 1 param version

I think that line should be changed to:
```
  var host = req ? (req.headers['x-forwarded-host'] || req.headers['host']) : window.location.host;
```
so it grabs host if x-forwarded-host is not set.

### PR DESCRIPTION
**Pull request by halkeye**
fixes #6 

Untested just freehanded it on the github UI

### CODE REVIEW

**Comment by jekrb** [comment]
Awesome, thank you!

**Comment by halkeye** [comment]
@jekrb i was thinking about it, blindly trusting x-forwarded-host can be considered a security risk, cause a user could change the url you hit if you are not behind a proxy/load balancer that doesn't set the header.

**Comment by jekrb** [comment]
@halkeye your PR has been published to npm as next-absolute-url@1.1.1

Also regarding your latest comment, we can _probably_ switch to just using `host` now instead of `x-forwarded-host`.  I think that we had to rely on that because of how `now dev` used to work (different ports for lambda functions), but it's probably worth investigating if that is different now.

**Comment by jekrb** [comment]
Original discussion about that: https://github.com/jekrb/next-absolute-url/issues/1

**Pull request merged**
